#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Round-trip тесты файлового слоя scripts/filemarks/.

Всё собирается в памяти и во временных каталогах:
  - минимальный PNG (IHDR/caBX/tEXt/IDAT/IEND) с ручной упаковкой чанков;
  - DOCX и ODT — это zip-контейнеры, которые тест создаёт через zipfile;
  - zip-бомба — валидный DOCX, у которого в central directory и local header
    записи docProps/core.xml завышен uncompressed size.

Проверяется главный контракт filemarks: clean должен давать файл, для
которого inspect больше не находит меток. Полезная нагрузка текста (пиксельные
данные PNG / document.xml DOCX / content.xml ODT) сохраняется байт-в-байт.
Медиа-части контейнера (word/media/*, Pictures/*, data-URI, вложенные PNG в
SVG) намеренно меняются: с них снимаются C2PA/EXIF, поэтому их полезная
нагрузка (пиксели) сохраняется, а байты файла — не обязаны совпадать (I.12).
Плюс проверяется отказ при zip-бомбе.
"""

import io
import os
import struct
import sys
import tempfile
import unittest
import zipfile
import zlib
from pathlib import Path

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS = os.path.join(ROOT, "scripts")
FILEMARKS = os.path.join(SCRIPTS, "filemarks")
if not os.path.isdir(FILEMARKS):
    # sdist вне дерева репозитория: файловый слой меток не входит в
    # pip-пакет (contract.v1.json), тесты слоя честно пропускаются.
    raise unittest.SkipTest("scripts/filemarks/ отсутствует (sdist): "
                            "файловые метки вне pip-пакета")
for p in (FILEMARKS, SCRIPTS):
    if p not in sys.path:
        sys.path.insert(0, p)
# filemarks — и пакет (scripts/filemarks/), и модуль (scripts/filemarks/
# filemarks.py); для _score_synthid нужен модуль — ставим его каталог выше.
sys.path.insert(0, FILEMARKS)

import container_meta  # noqa: E402
import filemarks  # noqa: E402
import image_meta  # noqa: E402
import text_layer  # noqa: E402

MAX_ZIP = container_meta.MAX_ZIP_DECOMPRESSED_BYTES


def _png_chunk(ctype, payload):
    crc = zlib.crc32(ctype)
    crc = zlib.crc32(payload, crc) & 0xFFFFFFFF
    return struct.pack(">I", len(payload)) + ctype + payload + struct.pack(">I", crc)


def _minimal_png():
    chunks = (
        (b"IHDR", struct.pack(">IIBBBBB", 1, 1, 8, 2, 0, 0, 0)),
        (b"caBX", b"c2pa manifest data"),
        (b"tEXt", b"Generated by OpenAI"),
        (b"IDAT", zlib.compress(b"\x00\xff\x00\x00")),
        (b"IEND", b""),
    )
    out = b"\x89PNG\r\n\x1a\n"
    for ctype, payload in chunks:
        out += _png_chunk(ctype, payload)
    return out


def _docx_with_ai_metadata():
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("word/document.xml",
                    "<w:document><w:body><w:p/></w:body></w:document>")
        zf.writestr("customXml/item1.xml", "<c2pa/>")
        zf.writestr("docProps/core.xml", "<dc:creator>Claude</dc:creator>")
        zf.writestr("docProps/app.xml", "<Application>Gemini</Application>")
    return buf.getvalue()


def _odt_with_ai_metadata():
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("mimetype", "application/vnd.oasis.opendocument.text",
                    compress_type=zipfile.ZIP_STORED)
        zf.writestr("content.xml", "<office:document-content/>")
        zf.writestr("meta.xml",
                    "<office:meta><meta:generator>Claude</meta:generator></office:meta>")
        zf.writestr("META-INF/manifest.xml",
                    '<manifest:manifest xmlns:manifest="urn:oasis">'
                    '<manifest:file-entry manifest:full-path="content.xml"/>'
                    '<manifest:file-entry manifest:full-path="c2pa.json"/>'
                    "</manifest:manifest>")
    return buf.getvalue()


def _patch_entry_uncompressed_size(data, entry_name, fake_size):
    """Патчит uncompressed size в local header и central directory одной записи."""
    data = bytearray(data)
    name = entry_name.encode("utf-8")
    pos = 0
    while pos + 30 <= len(data) and data[pos:pos + 4] == b"PK\x03\x04":
        nlen = struct.unpack_from("<H", data, pos + 26)[0]
        elen = struct.unpack_from("<H", data, pos + 28)[0]
        if data[pos + 30:pos + 30 + nlen] == name:
            struct.pack_into("<I", data, pos + 22, fake_size)
        csize = struct.unpack_from("<I", data, pos + 18)[0]
        pos = pos + 30 + nlen + elen + csize
    pos = data.find(b"PK\x01\x02")
    while pos >= 0 and pos + 46 <= len(data):
        nlen = struct.unpack_from("<H", data, pos + 28)[0]
        elen = struct.unpack_from("<H", data, pos + 30)[0]
        clen = struct.unpack_from("<H", data, pos + 32)[0]
        if data[pos + 46:pos + 46 + nlen] == name:
            struct.pack_into("<I", data, pos + 24, fake_size)
        pos = pos + 46 + nlen + elen + clen
    return bytes(data)


def _docx_zip_bomb():
    """Валидный DOCX, у которого docProps/core.xml обещает > MAX_ZIP байт."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_STORED) as zf:
        zf.writestr("word/document.xml", "<w:document/>")
        zf.writestr("docProps/core.xml", "<x/>")
    return _patch_entry_uncompressed_size(
        buf.getvalue(), "docProps/core.xml", MAX_ZIP + 1)


def _tagged_png():
    """PNG с C2PA-чанком caBX; полезная нагрузка — байты IDAT."""
    return _minimal_png()


def _docx_with_tagged_media():
    """DOCX с меченым PNG в word/media/ и невидимым символом в document.xml."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("word/document.xml",
                    "<w:document><w:p>текст\u200b</w:p></w:document>")
        zf.writestr("word/media/image1.png", _tagged_png())
    return buf.getvalue()


def _jpeg_with_icc(extra_app=None):
    """JPEG с APP2/ICC-профилем и (опционально) дополнительным APP-сегментом."""
    out = bytearray(b"\xff\xd8")

    def seg(marker, payload):
        out.extend(b"\xff" + bytes([marker]))
        out.extend(struct.pack(">H", len(payload) + 2))
        out.extend(payload)

    seg(0xE0, b"JFIF\x00\x01\x02\x00\x00\x01\x00\x01\x00\x00")
    seg(0xE2, b"ICC_PROFILE\x00\x01\x01" + b"\x00" * 64)  # APP2 ICC
    if extra_app:
        extra_app(out, seg)
    out.extend(b"\xff\xda")
    return bytes(out)


class TestFilemarksPNG(unittest.TestCase):
    def test_inspect_finds_c2pa_and_ai_text_chunk(self):
        with tempfile.TemporaryDirectory() as td:
            src = Path(td) / "x.png"
            src.write_bytes(_minimal_png())
            rep = image_meta.inspect_image(src)
            self.assertTrue(rep["has_c2pa"], rep["findings"])
            self.assertTrue(rep["has_ai_metadata"], rep["findings"])

    def test_clean_removes_metadata_and_keeps_pixel_payload(self):
        with tempfile.TemporaryDirectory() as td:
            src = Path(td) / "x.png"
            dst = Path(td) / "x.cleaned.png"
            src.write_bytes(_minimal_png())
            rep = image_meta.clean_image(src, dst)
            self.assertFalse(rep["still_has_c2pa"], rep["actions"])
            self.assertFalse(rep["still_has_ai_metadata"], rep["post_findings"])
            cleaned = dst.read_bytes()
            original = src.read_bytes()
            self.assertTrue(cleaned.startswith(b"\x89PNG\r\n\x1a\n"))
            self.assertEqual(
                original[original.index(b"IDAT"):original.index(b"IEND")],
                cleaned[cleaned.index(b"IDAT"):cleaned.index(b"IEND")])
            self.assertNotIn(b"caBX", cleaned)
            self.assertNotIn(b"Generated by OpenAI", cleaned)


class TestFilemarksJPEGICC(unittest.TestCase):
    """I.14: strip_jpeg сохраняет APP2/ICC (цветопередача), снимает остальные APP."""

    def test_strip_all_keeps_icc_removes_other_app(self):
        jpg = _jpeg_with_icc(extra_app=lambda out, seg: seg(0xEB, b"jumbf c2pa"))
        cleaned, actions = image_meta.strip_jpeg(jpg)
        self.assertIn(b"ICC_PROFILE", cleaned)
        self.assertNotIn(b"jumbf", cleaned)
        self.assertNotIn(b"c2pa", cleaned)

    def test_roundtrip_icc_survives(self):
        jpg = _jpeg_with_icc()
        cleaned, _ = image_meta.strip_jpeg(jpg)
        # round-trip: повторный прогон не удаляет ICC и не суёт его обратно
        cleaned2, _ = image_meta.strip_jpeg(cleaned)
        self.assertIn(b"ICC_PROFILE", cleaned2)
        self.assertEqual(cleaned, cleaned2)

    def test_non_icc_app2_removed(self):
        def mpf(out, seg):
            seg(0xE2, b"MPF\x00" + b"\x00" * 16)
        jpg = _jpeg_with_icc(extra_app=mpf)
        # MPF идёт отдельным APP2, а не ICC; при strip_all снимается
        cleaned, _ = image_meta.strip_jpeg(jpg)
        self.assertNotIn(b"MPF", cleaned)

    def test_inspect_does_not_find_icc_as_ai_marker(self):
        jpg = _jpeg_with_icc()
        has_c2pa, has_ai, findings = image_meta.inspect_jpeg(jpg)
        self.assertFalse(has_c2pa)
        self.assertFalse(has_ai)


class TestFilemarksDOCXODT(unittest.TestCase):
    def test_docx_inspect_clean_roundtrip(self):
        with tempfile.TemporaryDirectory() as td:
            src = Path(td) / "x.docx"
            dst = Path(td) / "x.cleaned.docx"
            src.write_bytes(_docx_with_ai_metadata())
            rep = container_meta.inspect_container(src)
            self.assertTrue(rep["has_c2pa"], rep["findings"])
            self.assertTrue(rep["has_ai_metadata"], rep["findings"])
            cleaned = container_meta.clean_container(src, dst)
            self.assertFalse(cleaned["still_has_c2pa"], cleaned["actions"])
            self.assertFalse(cleaned["still_has_ai_metadata"], cleaned["post_findings"])
            with zipfile.ZipFile(dst) as zf:
                names = set(zf.namelist())
                payload = zf.read("word/document.xml")
                core = zf.read("docProps/core.xml")
                app = zf.read("docProps/app.xml")
            self.assertFalse(any(n.startswith("customXml/") for n in names))
            self.assertEqual(payload,
                             "<w:document><w:body><w:p/></w:body></w:document>".encode("utf-8"))
            self.assertNotIn(b"Claude", core)
            self.assertNotIn(b"Gemini", app)

    def test_docx_nested_tagged_media_cleaned(self):
        """I.12: вложенный PNG с C2PA очищается; текст document.xml сохраняет
        полезную нагрузку, а невидимый символ слоя A снимается."""
        with tempfile.TemporaryDirectory() as td:
            src = Path(td) / "m.docx"
            dst = Path(td) / "m.cleaned.docx"
            src.write_bytes(_docx_with_tagged_media())
            rep = container_meta.inspect_container(src)
            self.assertTrue(any("вложенный носитель" in f for f in rep["findings"]),
                            rep["findings"])
            cleaned = container_meta.clean_container(src, dst)
            self.assertFalse(cleaned["still_has_c2pa"], cleaned["actions"])
            with zipfile.ZipFile(dst) as zf:
                media = zf.read("word/media/image1.png")
                doc = zf.read("word/document.xml").decode("utf-8")
            self.assertNotIn(b"caBX", media)
            # пиксельная полезная нагрузка PNG сохраняется байт-в-байт
            self.assertIn(b"IDAT", media)
            self.assertEqual(doc, "<w:document><w:p>текст</w:p></w:document>")

    def test_odt_inspect_clean_roundtrip(self):
        with tempfile.TemporaryDirectory() as td:
            src = Path(td) / "x.odt"
            dst = Path(td) / "x.cleaned.odt"
            src.write_bytes(_odt_with_ai_metadata())
            rep = container_meta.inspect_container(src)
            self.assertTrue(rep["has_c2pa"], rep["findings"])
            self.assertTrue(rep["has_ai_metadata"], rep["findings"])
            cleaned = container_meta.clean_container(src, dst)
            self.assertFalse(cleaned["still_has_c2pa"], cleaned["actions"])
            self.assertFalse(cleaned["still_has_ai_metadata"], cleaned["post_findings"])
            with zipfile.ZipFile(dst) as zf:
                self.assertNotIn(b"c2pa.json", zf.read("META-INF/manifest.xml"))
                self.assertNotIn(b"Claude", zf.read("meta.xml"))
                self.assertEqual(zf.read("content.xml"),
                                 "<office:document-content/>".encode("utf-8"))
                self.assertEqual(zf.read("mimetype"),
                                 "application/vnd.oasis.opendocument.text".encode("utf-8"))


class TestTextLayerA(unittest.TestCase):
    def test_clean_text_layer_removes_zero_width_and_soft_hyphen(self):
        if not text_layer.DETECTOR_OK:
            self.fail("check_markers не импортирован: слой A не проверяется")
        # Строку собираем через chr(), чтобы в исходнике теста не было
        # самих невидимых символов: тогда self-scan --scan честно его не
        # замечает. В памяти получаются настоящие U+200B и U+00AD.
        zws = chr(0x200B)
        shy = chr(0x00AD)
        text = "сло" + zws + "во и мягкий" + shy + "перенос"
        cleaned, n = text_layer.clean_text_layer(text)
        self.assertEqual(n, 2)
        self.assertNotIn(zws, cleaned)
        self.assertNotIn(shy, cleaned)


class TestTextLayerPUA(unittest.TestCase):
    """I.8: PUA-разделители снимаются слоем A, короткая форма сохраняет цифру."""

    def test_long_pua_removed(self):
        if not text_layer.DETECTOR_OK:
            self.fail("check_markers не импортирован: слой A не проверяется")
        text = "блок \ue200cite\ue202x\ue201 конец"
        cleaned, n = text_layer.clean_text_layer(text)
        self.assertEqual(n, 3)
        self.assertNotIn("\ue200", cleaned)
        self.assertNotIn("\ue201", cleaned)

    def test_short_pua_keeps_digit(self):
        if not text_layer.DETECTOR_OK:
            self.fail("check_markers не импортирован: слой A не проверяется")
        text = "конец предложения.\uea012\uea02"
        cleaned, n = text_layer.clean_text_layer(text)
        self.assertEqual(n, 2)
        self.assertEqual(cleaned, "конец предложения.2")
        self.assertNotIn("\uea01", cleaned)
        self.assertNotIn("\uea02", cleaned)


class TestTextLayerTagStrip(unittest.TestCase):
    """I.28: tag-символы снимаются, эмодзи-флаг сохраняется."""

    def test_flag_preserved(self):
        flag = "\U0001F3F4\U000E0067\U000E0062\U000E0067\U000E007F"
        cleaned, n = text_layer.clean_tag_strip(flag)
        self.assertEqual(n, 0)
        self.assertEqual(cleaned, flag)

    def test_solo_tag_and_format_chars_stripped(self):
        solo = "x\U000E0020y\u206Az\u034Fw"
        cleaned, n = text_layer.clean_tag_strip(solo)
        self.assertEqual(n, 3)
        self.assertEqual(cleaned, "xyzw")


class TestTextLayerMarkup(unittest.TestCase):
    """I.10: видимые copy-paste артефакты класса A снимаются безпотерно."""

    def test_markup_cases_removed(self):
        text = ("turn0search0 и :contentReference[oaicite:0]{index=0} "
                "и [cite: 8] и【1†source】.")
        cleaned, n = text_layer.clean_markup(text)
        self.assertGreaterEqual(n, 4)
        self.assertNotIn("turn0search0", cleaned)
        self.assertNotIn("contentReference", cleaned)

    def test_utm_cut_as_param_only(self):
        text = "см. https://example.com/?id=5&utm_source=chatgpt.com далее"
        cleaned, n = text_layer.clean_markup(text)
        self.assertEqual(n, 1)
        self.assertIn("https://example.com/?id=5", cleaned)
        self.assertNotIn("utm_source", cleaned)

    def test_utm_outside_url_untouched(self):
        text = "utm_source=openai упомянут в статье о трекинге"
        cleaned, n = text_layer.clean_markup(text)
        self.assertEqual(n, 0)
        self.assertIn("utm_source", cleaned)

    def test_think_block_removed_with_content(self):
        text = "Начало. <thinking>Сначала разберусь.</thinking> Ответ: 42."
        cleaned, n = text_layer.clean_markup(text)
        self.assertEqual(n, 1)
        self.assertNotIn("thinking", cleaned)
        self.assertNotIn("разберусь", cleaned)


class TestFilemarksZipBomb(unittest.TestCase):
    def test_inspect_zip_bomb_is_rejected_as_error(self):
        with tempfile.TemporaryDirectory() as td:
            src = Path(td) / "bomb.docx"
            src.write_bytes(_docx_zip_bomb())
            rep = container_meta.inspect_container(src)
            self.assertFalse(rep["has_c2pa"])
            self.assertFalse(rep["has_ai_metadata"])
            self.assertTrue(any("превышает лимит" in f for f in rep["findings"]),
                            rep["findings"])

    def test_clean_zip_bomb_raises_value_error(self):
        with tempfile.TemporaryDirectory() as td:
            src = Path(td) / "bomb.docx"
            dst = Path(td) / "bomb.cleaned.docx"
            src.write_bytes(_docx_zip_bomb())
            with self.assertRaises(ValueError):
                container_meta.clean_container(src, dst)


class TestSynthidInspectWiring(unittest.TestCase):
    """I.30: filemarks --inspect заполняет synthid честно, без checkout — unavailable."""

    def test_score_synthid_not_requested_without_upstream(self):
        res = filemarks._score_synthid(Path("x.png"), None)
        self.assertEqual(res["available"], False)
        self.assertIn("не запрошен", res["note"])

    def test_score_synthid_unavailable_with_bad_upstream(self):
        with tempfile.TemporaryDirectory() as td:
            res = filemarks._score_synthid(Path("x.png"), Path(td) / "нет_checkout")
            self.assertEqual(res["available"], False)

    def test_webp_exif_strip_roundtrip(self):
        webp = (b"RIFF" + struct.pack("<I", 4 + (8 + 8 + 8 + 8))
                + b"WEBP" + b"VP8X\x0a\x00\x00\x00" + b"\x00" * 10
                + b"EXIF" + struct.pack("<I", 4) + b"AIGC"
                + b"XMP " + struct.pack("<I", 4) + b"c2pa")
        cleaned, actions = image_meta.strip_webp(webp)
        self.assertNotIn(b"AIGC", cleaned)
        self.assertNotIn(b"c2pa", cleaned)
        has_c2pa, has_ai, findings = image_meta.inspect_webp(cleaned)
        self.assertFalse(has_c2pa)
        self.assertFalse(has_ai)


if __name__ == "__main__":
    unittest.main()