/* Generated by demo/generate_cleaner_rules.py; do not edit. */
const HUMANIZER_CLEANER_RULES = {
  "schema_version": 1,
  "rounds": 10,
  "layer_a": {
    "source": "(?:[​‌‎‏‪-‮⁠-⁤⁦-⁩﻿￹-￻]|(?<![🀀-🫿☀-➿️🇦-🇿])‍(?![🀀-🫿☀-➿️🇦-🇿]))|(?:­|[  　]|(?<![🀀-🫿☀-➿🇦-🇿©®‼⁉™ℹ↔-↙↩-↪⌚-⌛⌨⏏⏩-⏺Ⓜ▪-◾⤴-⤵⬀-⯿〰〽㊗㊙])[︀-️](?![🀀-🫿☀-➿🇦-🇿⃣]))|(?:[-])|(?:[])",
    "flags": "gu"
  },
  "tag_strip": {
    "source": "(?<![\\u{1f3f4}\\u{1f3f3}\\uFE0F\\u{e0000}-\\u{e007f}])[\\u{e0000}-\\u{e007f}\\u206A-\\u206F\\u180E\\u034F]",
    "flags": "gu"
  },
  "think": {
    "source": "<think(?:ing)?>.*?</think(?:ing)?>",
    "flags": "gsu"
  },
  "chain": {
    "source": "[A-Za-zА-Яа-яЁё)]\\+\\p{Nd}+(?:[A-Za-zА-Яа-яЁё&.\\- ]*[A-Za-zА-Яа-яЁё)]\\+\\p{Nd}+){1,3}",
    "flags": "gu"
  },
  "chain_numbers": {
    "source": "\\+\\p{Nd}+",
    "flags": "gu"
  },
  "markup": [
    {
      "name": "contentReference",
      "source": ":contentReference\\[oaicite:\\p{Nd}+\\]\\{index=\\p{Nd}+\\}",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "gemini_span",
      "source": "\\[span_\\p{Nd}+\\][\\[(](?:start_span|end_span)[\\])]",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "gemini_cite_n",
      "source": "\\[[Cc]ite:[\\t\\n\\v\\f\\r\\u001c-\\u001f\\u0020\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000]?\\p{Nd}+(?:,[\\t\\n\\v\\f\\r\\u001c-\\u001f\\u0020\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000]?\\p{Nd}+)*\\]",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "gemini_cite_start",
      "source": "\\[cite_start\\]",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "cite_turn",
      "source": "citeturn\\p{Nd}+[a-z]+\\p{Nd}+",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "deepseek_line_ref",
      "source": "【\\p{Nd}+†L\\p{Nd}+(?:-L?\\p{Nd}+)?】",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "assistants_source",
      "source": "【\\p{Nd}+(?::\\p{Nd}+)?†source】",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "generated_ref_id",
      "source": "citegenerated-reference-identifier",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "oai_citation",
      "source": "oai_citation:\\p{Nd}+‡",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "citation_n",
      "source": "\\[citation:\\p{Nd}+\\]",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "oaicite_short",
      "source": "oaicite:\\p{Nd}+",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "turn_search",
      "source": "turn\\p{Nd}+search\\p{Nd}+",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "turn_fetch",
      "source": "turn\\p{Nd}+fetch\\p{Nd}+",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "turn_file",
      "source": "turn\\p{Nd}+file\\p{Nd}+",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "turn_other",
      "source": "turn\\p{Nd}+(?:image|news|video|ref)\\p{Nd}+",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "copilot_caret",
      "source": "\\[\\^\\p{Nd}+\\^\\]",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "attributableIndex",
      "source": "(?<![A-Za-z0-9_])attributableIndex(?![A-Za-z0-9_])",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "attached_web_bracket",
      "source": "\\[(?:attached_file|web):\\p{Nd}+\\]",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "writing_block",
      "source": ":::[\\p{L}\\p{N}_]+\\{(?:[^\\n}\"]|\"[^\"]*\")*\\}",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "grok_render_json",
      "source": "\\[\\]\\(grok_render_citation_card_json=[^)]*\\)",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "attached_file",
      "source": "attached_file://[^\\t\\n\\v\\f\\r\\u001c-\\u001f\\u0020\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000]*",
      "flags": "gu",
      "protect_urls": true
    },
    {
      "name": "grok_card",
      "source": "grok_card://[^\\t\\n\\v\\f\\r\\u001c-\\u001f\\u0020\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000]*",
      "flags": "gu",
      "protect_urls": false
    },
    {
      "name": "vertexaisearch",
      "source": "(?:https?://)?vertexaisearch\\.cloud\\.google\\.com/grounding-api-redirect[^\\t\\n\\v\\f\\r\\u001c-\\u001f\\u0020\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000]*",
      "flags": "gu",
      "protect_urls": false
    },
    {
      "name": "perplexity_s3",
      "source": "(?:https?://)?[^\\t\\n\\v\\f\\r\\u001c-\\u001f\\u0020\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000]*ppl-ai-file-upload[^\\t\\n\\v\\f\\r\\u001c-\\u001f\\u0020\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000]*",
      "flags": "gu",
      "protect_urls": true
    }
  ],
  "utm": [
    {
      "source": "[?&]utm_source=chatgpt\\.com(?![A-Za-z0-9_.-])[^\\t\\n\\v\\f\\r\\u001c-\\u001f\\u0020\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000&#)`<>\"'«»]*",
      "flags": "gu"
    },
    {
      "source": "[?&]utm_source=openai(?![A-Za-z0-9_.-])[^\\t\\n\\v\\f\\r\\u001c-\\u001f\\u0020\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000&#)`<>\"'«»]*",
      "flags": "gu"
    },
    {
      "source": "[?&]utm_source=copilot\\.com(?![A-Za-z0-9_.-])[^\\t\\n\\v\\f\\r\\u001c-\\u001f\\u0020\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000&#)`<>\"'«»]*",
      "flags": "gu"
    },
    {
      "source": "[?&]referrer=grok\\.com[^\\t\\n\\v\\f\\r\\u001c-\\u001f\\u0020\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000&#)`<>\"'«»]*",
      "flags": "gu"
    }
  ],
  "url": {
    "source": "(?:https?://|www\\.)[^\\t\\n\\v\\f\\r\\u001c-\\u001f\\u0020\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000<>«»\"')\\]]+",
    "flags": "gu"
  },
  "tag_open": {
    "source": "<[a-zA-Z!/]",
    "flags": "gu"
  },
  "fence_open": {
    "source": "(?<![^]) {0,3}(`{3,}|~{3,})",
    "flags": "gu"
  },
  "emoji": {
    "source": "[🀀-🫿☀-➿️🇦-🇿]",
    "flags": "gu"
  },
  "whitespace": {
    "source": "[\\t\\n\\v\\f\\r\\u001c-\\u001f\\u0020\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000]",
    "flags": "gu"
  }
};
if (typeof module !== "undefined" && module.exports) module.exports = HUMANIZER_CLEANER_RULES;
if (typeof globalThis !== "undefined") globalThis.HUMANIZER_CLEANER_RULES = HUMANIZER_CLEANER_RULES;
