#!/usr/bin/env python3
"""Export canonical cleanup patterns; no independent browser regex catalogue."""
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "scripts" / "filemarks"))
sys.path.insert(0, str(HERE.parent / "scripts"))
import text_layer as core
import protected_regions as protection
from generate_js_rules import py_to_js, _PY_SPACE_CLASS, _WORD_CLASS


def convert(pattern):
    """Extend the demo converter for flags and escapes inside classes.

    Expand whitespace/word escapes inside classes before py_to_js, whose
    bracketed expansion is suitable outside classes only. Reject unsupported
    negated class escapes instead of silently diverging.
    """
    inline = ""
    while pattern.startswith("(?"):
        match = re.match(r"^\(\?([ms]+)\)", pattern)
        if not match:
            break
        inline += match[1]
        pattern = pattern[match.end():]
    out = []
    inside = False
    i = 0
    while i < len(pattern):
        char = pattern[i]
        if char == "\\" and i + 1 < len(pattern):
            escaped = pattern[i + 1]
            if inside and escaped in "swd":
                out.append({"s": _PY_SPACE_CLASS, "w": _WORD_CLASS,
                            "d": r"\p{Nd}"}[escaped])
            elif inside and escaped in "SWD":
                raise ValueError("Unsupported negated escape in class: " + escaped)
            else:
                out.append(pattern[i:i + 2])
            i += 2
            continue
        if char == "[":
            inside = True
        elif char == "]":
            inside = False
        out.append(char)
        i += 1
    source, flags = py_to_js("".join(out))
    # Unicode mode consumes code points, including in dot/negated classes.
    flags = "".join(dict.fromkeys(flags + inline + "u"))
    # Python anchors recognize LF only, unlike JS multiline anchors; Python
    # dot also excludes only LF, whereas JS dot excludes CR and U+2028/2029.
    translated = []
    inside = False
    i = 0
    while i < len(source):
        char = source[i]
        if char == "\\":
            translated.append(source[i:i + 2])
            i += 2
            continue
        if char == "[":
            inside = True
        elif char == "]":
            inside = False
        if not inside and char == "." and "s" not in flags:
            translated.append("[^\\n]")
        elif not inside and char == "^":
            translated.append("(?<![^])" if "m" not in flags else "(?<![^\\n])")
        elif not inside and char == "$":
            translated.append("(?=\\n?(?![^]))" if "m" not in flags else "(?=\\n|(?![^]))")
        else:
            translated.append(char)
        i += 1
    return {"source": "".join(translated), "flags": flags.replace("m", "")}


def build_js():
    if not core.DETECTOR_OK or core._PR is None:
        raise RuntimeError("Canonical cleaner dependencies unavailable")
    data = {
        "schema_version": 1,
        "rounds": core._CLEAN_ROUNDS,
        "layer_a": convert(core.layer_a_rx().pattern),
        "tag_strip": convert(core.TAG_STRIP_RX.pattern),
        "think": convert(core._THINK_RX.pattern),
        "chain": convert(core._CHAIN_RUN.pattern),
        "chain_numbers": convert(r"\+\d+"),
        "markup": [{"name": name, **convert(rx.pattern),
                    "protect_urls": not core._is_url_marker_name(name)}
                   for name, rx in core._compiled_markup()],
        "utm": [convert(rx.pattern) for rx, _ in core._utm_patterns()],
        "url": convert(protection.URL_RX.pattern),
        "tag_open": convert(protection._TAG_OPEN_RX.pattern),
        "fence_open": convert(protection._FENCE_OPEN_RX.pattern),
        "emoji": convert(protection._EMOJI_CH_RX.pattern),
        "whitespace": convert(r"\s"),
    }
    return ("/* Generated by demo/generate_cleaner_rules.py; do not edit. */\n"
            + "const HUMANIZER_CLEANER_RULES = "
            + json.dumps(data, ensure_ascii=False, indent=2) + ";\n"
            + 'if (typeof module !== "undefined" && module.exports) '
            + 'module.exports = HUMANIZER_CLEANER_RULES;\n'
            + 'if (typeof globalThis !== "undefined") '
            + 'globalThis.HUMANIZER_CLEANER_RULES = HUMANIZER_CLEANER_RULES;\n')


if __name__ == "__main__":
    output = HERE / "cleaner-rules.js"
    with output.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(build_js())
    print("Generated demo/cleaner-rules.js")
